In [54]:
import pandas as pd

In [55]:
data=pd.read_csv('laptop_price.csv',encoding='latin_1')

In [56]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [57]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [59]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [61]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [62]:
data['Weight']=data['Weight'].str.replace('kg',' ').astype('float')

In [63]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   float64
 11  Price_euros       1303 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 122.3+ KB

In [65]:
data.corr()['Price_euros']

C:\Users\Lasantha\AppData\Local\Temp\ipykernel_9560\703178330.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [66]:
data.value_counts('Company')

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Vero           4
Xiaomi         4
Google         3
Fujitsu        3
Chuwi          3
LG             3
Huawei         2
dtype: int64

In [67]:
def add_company(input):
    if input=='samsung' or input=='Razer' or input=='Mwdiacom' or input=='Microsoft' or input=='Vero' or input=='Xiaomi' or input=='Google' or input=='Fujitsu' or input=='Chuwi' or input=='LG' or input=='Huawei':
        return 'Other'
    else:
        return input
data['Company']=data['Company'].apply(add_company)

In [68]:
data['Company'].value_counts()

Dell        297
Lenovo      297
HP          274
Asus        158
Acer        103
MSI          54
Toshiba      48
Other        35
Apple        21
Samsung       9
Mediacom      7
Name: Company, dtype: int64

In [69]:
data['Product'].value_counts()

XPS 13                                     30
Inspiron 3567                              29
250 G6                                     21
Legion Y520-15IKBN                         19
Vostro 3568                                19
                                           ..
15-bw007nv (A10-9620P/6GB/128GB/Radeon      1
SmartBook 130                               1
A541NA-GO342 (N3350/4GB/500GB/Linux)        1
17-X047na (i3-6006U/8GB/1TB/W10)            1
V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)     1
Name: Product, Length: 618, dtype: int64

In [70]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [71]:
data['ScreenResolution'].value_counts()

Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              7
IPS Panel 1366x768                                 7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
1440x900                                           4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Touchscreen 1366x768                     3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: ScreenResolution, dtype: int64

In [72]:
data['TouchScreen']=data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['IPS']=data['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)

In [73]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [74]:
data['Cpu']=data['Cpu'].apply(lambda x: ' '.join(x.split()[0:3]))

In [75]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [76]:
data['Cpu'].value_counts()

Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
Intel Celeron Quad            8
AMD A6-Series 9220            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD A10-Series 9620P          2
Intel Atom X5-Z8350           2
AMD E-Series E2-9000e         2
Intel Xeon E3-1535M           2
Intel Xeon E3-1505M           2
AMD E-Series 7110             2
AMD A10-Series 9600P          2
AMD A6-Series A6-9220         2
AMD A10-Series A10-9620P      2
AMD Ryzen 1600                1
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
AMD E-Series 9000e            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
AMD E-Series 6110             1
Name: Cpu, dtype: int64

In [77]:
def set_processor(name):
    if name=='Intel Core i7' or name=='Intel Core i5' or name=='Intel Core i3':
        return name
    else:
        if name.split()[0]=='AMD':
            return 'AMD'
        else:
            return 'Other'
data['Cpu']=data['Cpu'].apply(set_processor)

In [78]:
data['Cpu'].value_counts()

Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: Cpu, dtype: int64

In [79]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5,8GB,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [80]:
data['Gpu'].value_counts()

Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
AMD Radeon R5 520            1
AMD Radeon R7                1
Intel HD Graphics 540        1
AMD Radeon 540               1
ARM Mali T860 MP4            1
Name: Gpu, Length: 110, dtype: int64

In [81]:
data['Gpu_name']=data['Gpu'].apply(lambda x:' '.join(x.split()[0:1]) )

In [82]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel

In [83]:
data['Gpu_name'].value_counts()

Intel     722
Nvidia    400
AMD       180
ARM         1
Name: Gpu_name, dtype: int64

In [84]:
data=data[data['Gpu_name']!='ARM']

In [85]:
data.shape

(1302, 15)

In [86]:
data['OpSys'].value_counts()

Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: OpSys, dtype: int64

In [87]:
def os(input):
    if input=='Windows 10' or input=='Windows 7' or input=='Windows 10 S':
        return 'Windows'
    elif input=='macOS' or input=='Mac OS X':
        return 'Mac'
    elif input=='Linux':
        return 'Linux'
    else:
        return 'Others'
data['OpSys']=data['OpSys'].apply(os)

In [88]:
data.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8GB,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5,8GB,Intel HD Graphics 620,Others,1.86,575.00,0,0,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7,16GB,AMD Radeon Pro 455,Mac,1.83,2537.45,0,1,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 650,Mac,1.37,1803.60,0,1,Intel

In [89]:
data['OpSys'].value_counts()

Windows    1125
Others       94
Linux        62
Mac          21
Name: OpSys, dtype: int64

In [90]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,TouchScreen,IPS,Gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5,8GB,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5,8GB,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel

In [91]:
data=data.drop(columns=['laptop_ID','Inches','Product','ScreenResolution','Gpu'])

In [92]:
data.head()

,Company,TypeName,Cpu,Ram,OpSys,Weight,Price_euros,TouchScreen,IPS,Gpu_name
0,Apple,Ultrabook,Intel Core i5,8GB,Mac,1.37,1339.69,0,1,Intel
1,Apple,Ultrabook,Intel Core i5,8GB,Mac,1.34,898.94,0,0,Intel
2,HP,Notebook,Intel Core i5,8GB,Others,1.86,575.00,0,0,Intel
3,Apple,Ultrabook,Intel Core i7,16GB,Mac,1.83,2537.45,0,1,AMD
4,Apple,Ultrabook,Intel Core i5,8GB,Mac,1.37,1803.60,0,1,Intel

In [93]:
data=pd.get_dummies(data)

In [94]:
data.head()

,Weight,Price_euros,TouchScreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,...,Ram_64GB,Ram_6GB,Ram_8GB,OpSys_Linux,OpSys_Mac,OpSys_Others,OpSys_Windows,Gpu_name_AMD,Gpu_name_Intel,Gpu_name_Nvidia
0,1.37,1339.69,0,1,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
1,1.34,898.94,0,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
2,1.86,575.00,0,0,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0
3,1.83,2537.45,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,1.37,1803.60,0,1,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0

In [95]:
data.shape

(1302, 42)

In [96]:
x=data.drop(['Price_euros'],axis=1)
y=data.Price_euros

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

In [100]:
print(len(xtrain))
print(len(xtest))

976
326

In [101]:
acc_list=[]
    
def model_accuracy(model):
    model.fit(xtrain,ytrain)
    acc=model.score(xtest,ytest)
    acc_list.append(acc)
    print(model,acc)
acc_list

[]

In [102]:
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model_li=LinearRegression()
model_dc=DecisionTreeRegressor()
model_lss=Lasso()
model_rf=RandomForestRegressor()
model_list=[]
model_list.extend([model_li,model_dc,model_lss,model_rf])

In [103]:
model_list

[LinearRegression(), DecisionTreeRegressor(), Lasso(), RandomForestRegressor()]

In [104]:
for i in model_list:
    model_accuracy(i)

LinearRegression() -2.134980201366425e+23
DecisionTreeRegressor() 0.6975440169135936
Lasso() 0.6778669934226954
RandomForestRegressor() 0.7705545704270911

In [105]:
import pickle

In [106]:
with open('predictor.pickle','wb')as file:
    pickle.dump(model_rf,file)

In [113]:
list_cols=xtrain.columns.tolist()

In [146]:
pred_list=[]
for i in list_cols:
    if i=='Weight':
        pred_list.append(1.5)
    elif i=='TouchScreen':
        pred_list.append(1)
    elif i=='IPS':
        pred_list.append(1)
    elif i=='Company_Apple':
        pred_list.append(1)
    elif i=='TypeName_Workstation':
        pred_list.append(1)
    elif i=='Cpu_Intel Core i7':
        pred_list.append(1)
    elif i=='Ram_4GB':
        pred_list.append(1)
    elif i=='OpSys_Mac':
        pred_list.append(1)
    elif i=='Gpu_name_Nvidia':
        pred_list.append(1)
    else:
        pred_list.append(0)

In [156]:
pred_list

[1.5,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1]

In [157]:
model_rf.predict([pred_list])

C:\Users\Lasantha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1783.22633333])